const {chromium}=require('C:/Users/pc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const theme of ['light','dark']){await page.emulateMedia({colorScheme:theme,reducedMotion:'reduce'});for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});await page.goto('http://localhost:5173/',{waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('data-theme'),theme);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'qa/revamp-'+theme+'-'+width+'.png',fullPage:true});console.log('Layout',theme,width,'passed');}}
await page.getByRole('button',{name:'Switch to light mode'}).click();await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
await page.getByRole('button',{name:'Explore Haqooq AI case study',exact:true}).click();assert(await page.getByRole('dialog').isVisible());await page.keyboard.press('Escape');assert(!await page.getByRole('dialog').isVisible());
await page.getByRole('button',{name:'Mobile',exact:true}).click();assert.equal(await page.locator('.additional-project').count(),4);await page.getByRole('button',{name:'All',exact:true}).click();assert.equal(await page.locator('.additional-project').count(),9);
await page.locator('.office-project summary').first().click();assert(await page.locator('.office-contribution').first().isVisible());
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Open navigation'}).click();await page.locator('#mobile-nav a[href="#work"]').click();assert(!await page.locator('#mobile-nav').count());assert.deepEqual(errors,[]);console.log('Persistence, case studies, filters, professional details, mobile menu and runtime checks passed');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
