import { ArrowUpRight, AudioLines, BookOpen, FileText, Fingerprint, Mic, ScanLine, Sparkles } from 'lucide-react';
import type { Project } from '../data/portfolio';
export function ProjectVisual({project,detail=false}:{project:Project;detail?:boolean}) {
 if(project.image)return <div className={`project-visual artwork-visual artwork-${project.id}`}><img src={project.image} srcSet={project.imageSmall ? `${project.imageSmall} ${project.imageSmallWidth ?? 800}w, ${project.image} ${project.imageWidth ?? 1600}w` : undefined} sizes={detail ? '(max-width: 600px) 90vw, 700px' : ['haqooq','sahara'].includes(project.id) ? '(max-width: 600px) 90vw, 44vw' : '(max-width: 800px) 94vw, 88vw'} alt={project.imageAlt ?? `${project.name} conceptual project artwork`} loading={detail?'eager':'lazy'} decoding="async" width={project.imageWidth ?? 1600} height={project.imageHeight ?? 900}/>{project.imageCredit === "generated" && <span className="artwork-caption"><span>{project.name}</span><span>CONCEPT ARTWORK</span></span>}{project.id === "sahara" && <span className="sahara-cover-copy"><span className="eyebrow">SAHARA AI</span><strong>Everyday help.<br/><em>Made simpler.</em></strong><span className="sahara-cover-detail">Voice. Vision.<br/>A simpler way to connect.</span></span>}{project.id === "haqooq" && !detail && <span className="screenshot-label">HAQOOQ AI / PRODUCT OVERVIEW</span>}</div>;
 return <div className={`project-visual visual-${project.id}`} aria-label={`${project.name} conceptual visual`}>
 <span className="concept-label">CONCEPT STUDY / {project.name.toUpperCase()}</span>
 {project.id==='trustfin'&&<><div className="finance-orbits" aria-hidden="true"><i/><i/><i/><span>t<span>f</span><sup>↗</sup></span></div><div className="trust-languages"><span>ENGLISH</span><span lang="ur" dir="rtl">اردو</span><span>ROMAN URDU</span></div><div className="evidence-chip"><Fingerprint size={19}/> Built around verified sources <span>↗</span></div></>}
 {project.id==='haqooq'&&<><div className="legal-emblem"><span>ح</span><div>HAQOOQ<span>Knowledge. Grounded.</span></div></div><div className="source-stack"><div><BookOpen size={16}/><span>Constitution of Pakistan</span><ArrowUpRight size={16}/></div><div><FileText size={16}/><span>Pakistan Penal Code</span><ArrowUpRight size={16}/></div><div><ScanLine size={16}/><span>Source-grounded retrieval</span></div></div></>}
 {project.id==='sahara'&&<><div className="sahara-word">A little help.<br/>A world of access.</div><div className="voice-orb"><AudioLines size={62} strokeWidth={1}/></div><div className="voice-pill"><Mic size={18}/> A voice-first experience <span>●</span></div></>}
 {project.id==='smarthire'&&<><div className="hire-flow"><div className="document-shape"><FileText size={28}/><span>RESUME</span><i/><i/><i/><i/></div><span className="flow-line"/><div className="hire-core"><Sparkles size={34}/><span>Context<br/>meets capability.</span></div><span className="flow-line"/><div className="hire-output"><span>Job requirements</span><span>Candidate context</span><span>Interview questions</span></div></div><div className="visual-bottom-label">DOCUMENTS → CONTEXT → EVALUATION</div></>}
 {project.id==='islamic'&&<><div className="islamic-title">A moment<br/>of connection.<span>ISLAMIC INSIGHTS</span></div><div className="phone-concept"><div className="phone-top"/><span className="phone-label">ISLAMIC INSIGHTS</span><span className="arabic" lang="ar" dir="rtl">القرآن الكريم</span><span>The Holy Quran</span><div className="quran-navigation">Surah <span>Juz</span> Sajdah</div><div className="phone-feature"><BookOpen size={19}/><span>Quran & reciters</span></div><div className="phone-feature"><span>◷</span><span>Prayer timings</span></div><div className="phone-feature"><span>⌖</span><span>Qibla direction</span></div><div className="phone-bottom"/></div></>}
 </div>;
}



