import { Certifications } from '../components/Certifications';
import { useState } from 'react';

import { capabilities } from '../data/portfolio';
import { Reveal,SectionLabel } from '../components/Reveal';
export function Intersection(){return <section id="intersection" className="intersection section"><Reveal><div className="intersection-top"><span className="eyebrow">WHERE THE DISCIPLINES MEET</span><span className="eyebrow">THE CONNECTING THREAD</span></div><h2>FINTECH <span>×</span><br/>ENGINEERING <span>×</span><br/><span className="accent">ARTIFICIAL INTELLIGENCE</span></h2><div className="intersection-bottom"><p>Understanding financial workflows.<br/>Engineering the application.<br/>Bringing intelligence into the experience.</p><div className="connection-path"><span>Banking workflows</span><i>↓</i><span>Mobile / APIs / Data</span><i>↓</i><span>RAG / LLMs / Documents</span></div></div></Reveal></section>;}
export function Capabilities(){const[active,setActive]=useState(0);return <section id="capabilities" className="section capabilities"><Reveal><SectionLabel number="05">CAPABILITIES</SectionLabel><div className="section-heading"><h2>Tools change.<br/><span className="muted">The craft stays.</span></h2><p>A stack shaped by the problem.<br/>A perspective shaped by building.</p></div><div className="capability-layout"><div className="capability-tabs" role="tablist" aria-label="Engineering capabilities" aria-orientation="vertical">{capabilities.map((c,i)=><button key={c.name} id={`cap-tab-${i}`} role="tab" aria-selected={active===i} aria-controls={`cap-panel-${i}`} tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{let next=active;if(e.key==='ArrowDown')next=(active+1)%capabilities.length;else if(e.key==='ArrowUp')next=(active+capabilities.length-1)%capabilities.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=capabilities.length-1;else return;e.preventDefault();setActive(next);document.getElementById(`cap-tab-${next}`)?.focus();}}><span>0{i+1}</span>{c.name}</button>)}</div><div className="capability-panel" role="tabpanel" id={`cap-panel-${active}`} aria-labelledby={`cap-tab-${active}`} tabIndex={0}><span className="capability-symbol" aria-hidden="true">{['↗','✳','⌘','⇄','⌗'][active]}</span><h3>{capabilities[active].description}</h3><div className="tags">{capabilities[active].tech.map(t=><span key={t}>{t}</span>)}</div></div></div></Reveal><Reveal className="education"><div><span className="eyebrow">FOUNDATIONS / 2019 — 2023</span><h3><a className="organization-link" href="https://iqra.edu.pk/" target="_blank" rel="noopener noreferrer">Iqra University</a></h3><p>BS Computer Science · Karachi, Pakistan</p></div><div><span className="eyebrow">FINAL YEAR PROJECT</span><h4>Event Manager / Society Portal</h4><p>Built with Microsoft Power Platform: Power Pages, Canvas Apps, Dataverse, Power Automate and AI Builder, with PCF, FetchXML, model-driven apps, Business Process Flows and role-based functionality.</p></div></Reveal><Certifications/></section>;}




