import { useEffect, useState } from 'react';
import { AnimatePresence, motion, useMotionValue, useSpring, useReducedMotion } from 'framer-motion';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { links } from '../data/portfolio';
const domains=['Mobile engineering','FinTech & banking','AI / LLM systems','Web engineering','Data & systems'];
export function Hero(){const [domain,setDomain]=useState(0);const reduced=useReducedMotion(); const x=useMotionValue(0),y=useMotionValue(0);const sx=useSpring(x,{stiffness:60,damping:25}),sy=useSpring(y,{stiffness:60,damping:25});
 useEffect(()=>{if(reduced)return;const timer=window.setInterval(()=>setDomain(v=>(v+1)%domains.length),3600);return()=>clearInterval(timer);},[reduced]);
 return <section id="home" className="hero" onPointerMove={e=>{if(e.pointerType==='mouse'&&!reduced){const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.018);y.set((e.clientY-r.top-r.height/2)*.018);}}} onPointerLeave={()=>{x.set(0);y.set(0);}}>
 <div className="hero-topline"><span className="eyebrow">Software Engineer & Consultant</span><span className="eyebrow location">KARACHI, PK <span>24.86° N / 67.01° E</span></span></div>
 <motion.div className="hero-heading" initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.85}}><div className="name-line">MUHAMMAD</div><h1>OSAMA NOOR<span className="name-star">✳</span></h1></motion.div>
 <div className="hero-main"><div className="hero-story"><p className="hero-statement">Different disciplines.<br/><span>One connected perspective.</span></p><p className="hero-description">I build at the intersection of mobile, banking and AI — connecting thoughtful interfaces with the systems behind them.</p><div className="role-reel"><span className="role-mark"/><AnimatePresence mode="wait"><motion.span key={domain} initial={{y:16,opacity:0,filter:'blur(4px)'}} animate={{y:0,opacity:1,filter:'blur(0px)'}} exit={{y:-16,opacity:0,filter:'blur(4px)'}} transition={{duration:.4}}>{domains[domain]}</motion.span></AnimatePresence></div><div className="hero-actions"><a className="button primary" href="#work">Explore my work <ArrowDown size={17}/></a><a className="text-link" href={links.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={17}/></a></div></div>
 <motion.div className="system-map" style={{x:sx,y:sy}}><div className="map-caption">FIG. 01 — CONNECTED DISCIPLINES</div><svg viewBox="0 0 620 340" fill="none" aria-hidden="true"><path d="M90 90L310 165 495 65M310 165L530 250M310 165L155 285M90 90L155 285 530 250 495 65 90 90"/><circle cx="310" cy="165" r="88"/><circle cx="310" cy="165" r="118" strokeDasharray="2 8"/><path className="map-signal" d="M90 90L310 165 530 250"/></svg><a href="#capabilities" className="map-node node-mobile"><span>01</span>MOBILE <ArrowUpRight size={12}/></a><a href="#intersection" className="map-node node-fintech"><span>02</span>FINTECH <ArrowUpRight size={12}/></a><a href="#work" className="map-node node-ai"><span>03</span>AI / LLM <ArrowUpRight size={12}/></a><a href="#capabilities" className="map-node node-systems"><span>04</span>SYSTEMS <ArrowUpRight size={12}/></a><div className="map-center"><span>ENGINEER.</span><span>CONNECT.</span><span>BUILD.</span></div><span className="map-coordinate">MOBILE × FINTECH × AI</span></motion.div></div>
 <div className="hero-footer"><span>SOFTWARE ENGINEER <i>/</i> CONSULTANT <i>/</i> AI BUILDER</span><a href="#about">SCROLL TO CONNECT <ArrowDown size={14}/></a></div></section>;
}

